ruby-on-rails/e-navigator/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords"
  }
  devise_scope :user do
    root "users/sessions#new"
  end
  resources :users, only: [:index, :show] do
    resources :interviews, except: [:show] do
      member do
        post 'approve'
      end
      collection do
        post 'select_approver'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby-on-rails/e-navigator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>e-Navigator_石田隼人</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p><%= link_to "トップ", users_path %></p>
      <p><%= link_to "プロフィール編集", edit_user_registration_path %></p>
      <p><%= link_to "#{current_user.name}さんの面接一覧", user_interviews_path(current_user.id) %></p>
      <p><%= link_to "メール一覧",
            "https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin" %>
      </p>
      <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトします。宜しいですか?" } %></p>
    <% else %>
      <p><%= link_to "新規登録", new_user_registration_path %></p>
      <p><%= link_to "ログイン", new_user_session_path %></p>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>