ruby-on-rails/e-navigator/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: "users/registrations",
  sessions: "users/sessions",
  passwords: "users/passwords"
  }
  devise_scope :user do
    root "users/sessions#new"
  end
  resources :users, only: [:index, :show] do
    resources :interviews, except: [:show] do
      member do
        post 'approve'
      end
      collection do
        post 'select_approver'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby-on-rails/e-navigator/app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_user, only: [:index, :new, :create, :select_approver]
  before_action :set_interview, only: [:edit, :update, :destroy, :approve]

  # GET /users/:user_id/interviews
  def index
    @interviews = @user.interviews.order(datetime: 'asc')
    @approved_interview = @interviews.find_by(status: 1)
    # form_tag用に他ユーザー情報を代入します
    @email = User.where.not(id: current_user.id).pluck(:email)
  end

  # GET /users/:user_id/interviews/new
  def new
    @interview = Interview.new
  end

  # POST /users/:user_id/interviews
  def create
    unless current_user?(@user.id)
      flash[:notice] = "他のユーザーの面接日時の登録は許可されていません"
      redirect_to users_path
    else
      @interview = @user.interviews.new(interview_params)
      if @interview.save
        flash[:notice] = "面接日時を登録しました"
        redirect_to user_interviews_path
      else
        render :new
      end
    end
  end

  # GET /users/:user_id/interviews/:id/edit
  def edit
  end

  # PATCH /users/:user_id/interviews/:id
  def update
    unless current_user?(@interview.user_id)
      flash[:notice] = "他のユーザーの面接日時の変更は許可されていません"
      redirect_to users_path
    else
      @interview.update(interview_params)
      flash[:notice] = "面接日時を変更しました"
      redirect_to user_interviews_path
    end
  end

  # DELETE /users/:user_id/interviews/:id
  def destroy
    @interview.destroy
    flash[:notice] = "面接日時を削除しました"
    redirect_to user_interviews_path
  end

  # POST /users/:user_id/interviews/select_approver
  def select_approver
    @approver = User.find_by(email: approver_params[:email])
    # Mailerの名前を変更しました
    InterviewMailer.apply(@user, @approver).deliver
    flash[:notice] = "面接日時を申請しました"
    redirect_to user_interviews_path
  end

  # POST /users/:user_id/interviews/:id/approve
  def approve
    if @interview.datetime < DateTime.now
      flash[:notice] = "過去の日時を承認することは出来ません"
      redirect_to user_interviews_path
    else
      @interview.approved!
      # 以下、承認した日時以外を否認状態にする
      interviews = Interview.where(user_id: @interview.user_id).where.not(id: @interview.id)
      interviews.each do |interview|
        interview.declined!
        rescue ActiveRecord::RecordInvalid
      end
      @approver = current_user
      # Mailerの名前を変更しました
      InterviewMailer.approve(@approver, @interview).deliver
      flash[:notice] = "面接日時を承認しました"
      redirect_to user_interviews_path
    end
  end

  private

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    def set_interview
      @interview = Interview.find(params[:id])
    end

    def interview_params
      params.require(:interview).permit(:datetime)
    end

    # form_tagに変えたので、.require(:user)を削除しました
    def approver_params
      params.permit(:email)
    end

    def current_user?(id)
      current_user.id == id
    end
end

ruby-on-rails/e-navigator/app/helpers/interviews_helper.rb
module InterviewsHelper
end

ruby-on-rails/e-navigator/app/views/interviews/_form.html.erb
<% if @interview.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <ul>
    <% @interview.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.label :面接日時 %><br />
  <%== sprintf(
    f.datetime_select(
    :datetime,
    use_month_numbers: true,
    start_year: Time.now.year,
    end_year: Time.now.year,
    minute_step: 30,
    date_separator: '%s',
    datetime_separator: '%s'),
    '年', '月', '日') %>
</div>

ruby-on-rails/e-navigator/app/views/interviews/_select.html.erb
<% unless @approved_interview.nil? %>
  <h3>確定面接日時：<%= @approved_interview.datetime.strftime("%Y年%m月%d日 %H時%M分") %></h3>
<% end %>
<h4>面接日程を変更する場合は以下から選んでください。</h4>
<table>
  <tr>
    <th>面接日時</th>
  </tr>
  <% @interviews.each do |interview| %>
  <tr>
    <td>
      <%= link_to interview.datetime.strftime("%Y年%m月%d日 %H時%M分"),
          approve_user_interview_path(@user, interview),
          method: :post,
          data: { confirm: "#{interview.datetime.strftime("%Y年%m月%d日 %H時%M分")}を面接日時に確定します。宜しいですか?" }
      %>
    </td>
  </tr>
  <% end %>
</table>
<% if current_user.id == @user.id %>
  <br><%= link_to "新規面接登録", new_user_interview_path(@user) %><br>
<% end %>

ruby-on-rails/e-navigator/app/views/interviews/edit.html.erb
<h2>面接日程変更</h2>
<%= form_for @interview, url: {action: :update} do |f| %>
<%= render 'form', f: f %>
<div class="actions">
  <%= f.submit "変更" %>
</div>
<% end %>
<br>
<%= link_to "戻る", :back %>

ruby-on-rails/e-navigator/app/views/interviews/index.html.erb
<h2><%= @user.name %>さんの面接一覧</h2>
<% unless current_user.id == @user.id %>
  <%= render 'select' %>
<% else %>
  <% unless @approved_interview.nil? %>
    <h3>確定面接日時：<%= @approved_interview.datetime.strftime("%Y年%m月%d日 %H時%M分") %></h3>
  <% end %>
  <table>
    <tr>
      <th>面接日時</th>
      <th>承認状態</th>
      <% if current_user.id == @user.id %>
      <th>削除</th>
      <% end %>
    </tr>
    <% @interviews.each do |interview| %>
    <tr>
      <td>
      <% if current_user.id == @user.id && interview.suspended? %>
        <%= link_to interview.datetime.strftime("%Y年%m月%d日 %H時%M分"), edit_user_interview_path(@user, interview) %>
      <% else %>
        <%= interview.datetime.strftime("%Y年%m月%d日 %H時%M分") %>
      <% end %>
      </td>
      <td>
      <%= interview.status_i18n %>
      </td>
      <td>
      <% if current_user.id == @user.id && interview.suspended? %>
        <%= link_to "削除", user_interview_path(@user, interview), method: :delete, data: { confirm: "削除します。宜しいですか?" } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  <br>
  <div class="field">
     <!-- モデルを意識しないform_tagに変更しました -->
    <%= form_tag(action: :select_approver, method: :post) do %>
      <%= label_tag :申請先選択 %>
      <br>
      <%= select_tag :email, options_for_select(@email) %>
      <br>
      <%= submit_tag :申請 %>
    <% end %>
  </div>
  <% if current_user.id == @user.id %>
    <br>
    <%= link_to "新規面接登録", new_user_interview_path(@user) %><br>
  <% end %>
<% end %>
<br>
<%= link_to "戻る", :back %>

ruby-on-rails/e-navigator/app/views/interviews/new.html.erb
<h2>新規面接登録</h2>
<%= form_for @interview, url: {action: :create} do |f| %>
<%= render 'form', f: f %>
<div class="actions">
  <%= f.submit "新規面接登録" %>
</div>
<% end %>
<br>
<%= link_to "戻る", :back %>