ruby-on-rails/perfect-ruby-on-rails/config/routes.rb
Rails.application.routes.draw do
  root   'events#index'
  get    '/status'                  => 'status#index', defaults: { format: :json }
  get    '/auth/:provider/callback' => 'sessions#create'
  delete '/logout'                  => 'sessions#destroy'

  resources :events do
    resources :tickets, only: [:new, :create, :destroy]
  end

  resource :retirements, only: [:new, :create]
end

ruby-on-rails/perfect-ruby-on-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby-on-rails/perfect-ruby-on-rails/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :tickets, dependent: :destroy
  has_one_attached :image

  attr_accessor :remove_image

  before_save :remove_image_if_user_accept

  validates :name, presence: true, length: { maximum: 50 }
  validates :place, presence: true, length: { maximum: 10000 }
  validates :content, presence: true, length: { maximum: 2000 }
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at
  validates :image,
    content_type: [:png, :jpg, :jpeg],
    size: { less_than_or_equal_to: 10.megabytes },
    dimension: { width: { max: 2000 }, height: { max: 2000 } }

  scope :default, -> { where('start_at >= ?', Time.zone.now).order(:start_at, :name) }

  def self.ransackable_attributes(auth_object = nil)
    [
      'name',
      'place',
      'content',
      'start_at',
      'end_at'
    ]
  end

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  def has_image_to_show?
    self.image.attached? && self.image.blob&.persisted?
  end

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at
    errors.add(:start_at, 'は終了時刻より前の時刻を指定してください') if start_at.floor >= end_at.floor
  end

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

ruby-on-rails/perfect-ruby-on-rails/app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: 'owner_id'
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider  = auth_hash[:provider]
    uid       = auth_hash[:uid]
    nickname  = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    self.find_or_create_by!(provider: provider, uid: uid) { |user|
      user.name      = nickname
      user.image_url = image_url
    }
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    errors.add(:base, '公開中の未終了イベントが存在します。') if created_events.where(':now < end_at', now: now).exists?
    errors.add(:base, '未終了の参加イベントが存在します。') if participating_events.where(':now < end_at', now: now).exists?
    throw(:abort) if errors
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  private

  def logged_in?
    # Return false in case of false and nil
    # Otherwise, return true
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end

  def paginate_per
    session[:paginate_per] = params[:per] if params[:per].present?
  end

  def keep_last_pagination_data
    session[:last_pagination_data] = {
      params: request.query_parameters,
      controller: controller_name,
      action: action_name
    }
  end

  def load_pagination_params(action)
    data = session[:last_pagination_data].presence
    if data['controller'] == controller_name && data['action'] == action.to_s
      session[:last_pagination_data] = nil
      ret = data['params']
    end
  end

  def redirect_with_kept_pagination_params(action:, **args)
    redirect_to({ action:, params: load_pagination_params(action) }, args)
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show]
  before_action :set_event, only: :show
  before_action :set_event_of_current_user, only: [:edit, :update, :destroy]

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result.page(params[:page]).per(paginate_per).default
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'イベントを登録しました'
    else
      render :new
    end
  end

  def show
    @ticket  = current_user&.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'イベントを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy!
    redirect_to root_path, notice: 'イベントを削除しました'
  end

  private

  def event_params
    params.expect(event: [:name, :place, :content, :start_at, :end_at, :image, :remove_image])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_event_of_current_user
    @event = current_user.created_events.find(params[:id])
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/retirements_controller.rb
class RetirementsController < ApplicationController
  def new; end

  def create
    return unless current_user.destroy
    reset_session
    redirect_to root_path, notice: '退会が完了しました'
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:create]

  def create
    user = User.find_or_create_from_auth_hash!(request.env['omniauth.auth'])
    session['user_id'] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/status_controller.rb
class StatusController < ApplicationController
  skip_before_action :authenticate

  def index; end
end

ruby-on-rails/perfect-ruby-on-rails/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ApplicationController::RoutingError, 'ログイン状態で TicketsController#new にアクセスされました'
  end

  def create
    event = Event.find(params[:event_id])
    @ticket = current_user.tickets.build { |t|
      t.event = event
      t.comment = params[:ticket][:comment]
    }
    return unless @ticket.save
    redirect_to event, notice: 'このイベントに参加表明しました'
  end

  def destroy
    ticket = current_user.tickets.find_by(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/helpers/event_helper.rb
module EventHelper
  def show_image_if_attached(event)
    return unless event.has_image_to_show?
    image_tag event.image.variant(resize_to_fit: [200, 200]), class: 'img-thumnail d-block mb-3'
  end
end

ruby-on-rails/perfect-ruby-on-rails/app/views/application/_errors.html.erb
<div class="alert alert-danger">
  <ul class="mb-0">
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/_form.html.erb
<%= form_with(model: event, class: 'form-horizontal') do |f| %>
  <% if event.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% event.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_at %>
    <div>
      <%= f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at %>
    <div>
      <%= f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= show_image_if_attached(event) %>
    <%= f.file_field :image, class: 'form-control-file' %>
  </div>
  <% if event.has_image_to_show? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :remove_image %>
        画像を削除する
      </label>
    </div>
  <% end %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary btn-lg btn-block' %>
      </div>
      <div class="col-auto">
        <%= link_to '戻る', 'javascript:history.back()', class: 'btn btn-secondary btn-lg btn-block' %>
      </div>
    </div>
  </div>
<% end %>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/_index_search_form.html.erb
<div class="panel panel-default panel-search">
  <div class="panel-body">
    <%= search_form_for(@q, class: 'mb-5') do |f| %>
      <div class="row form-group">
        <div class="col-sm-6">
          <%= f.label :name_cont, Event.human_attribute_name(:name), class: 'control-label col-sm-5 nowrap' %>
          <div class="col-sm-11 col-md-9">
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-6">
          <%= f.label :place_cont, Event.human_attribute_name(:place), class: 'control-label col-sm-5 nowrap' %>
          <div class="col-sm-11 col-md-9">
            <%= f.search_field :place_cont, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-12">
          <%= f.label :content_cont, Event.human_attribute_name(:content), class: 'control-label col-sm-5 nowrap' %>
          <div class="col-sm-11 col-md-10">
            <%= f.search_field :content_cont, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="row form-group">
        <div class="col-sm-6">
          <%= f.label :start_at_gteq, Event.human_attribute_name(:start_at), class: 'control-label col-sm-5 nowrap' %>
          <div class="col-sm-11 col-md-9">
            <%= f.datetime_field :start_at_gteq, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-6">
          <%= f.label :end_at_lteq, Event.human_attribute_name(:end_at), class: 'control-label col-sm-5 nowrap' %>
          <div class="col-sm-11 col-md-9">
            <%= f.datetime_field :end_at_lteq, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="form-btn-field">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/_show_body.html.erb
<% if @event.image.attached? %>
  <div class="row mb-2">
    <div class="col-8">
      <%= image_tag @event.image, width: 180 %>
    </div>
  </div>
<% end %>
<div id="content" class="card mb-2">
  <h5 class="card-header"><%= Event.human_attribute_name(:content) %></h5>
  <div class="card-body">
    <p class="card-text"><%= @event.content %></p>
  </div>
</div>
<div id="time-from-to" class="card mb-2">
  <h5 class="card-header"><%= Event.human_attribute_name(:time) %></h5>
  <div class="card-body">
    <p class="card-text">
      <%= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}" %>
    </p>
  </div>
</div>
<div id="place" class="card mb-2">
  <h5 class="card-header"><%= Event.human_attribute_name(:place) %></h5>
  <div class="card-body">
    <p class="card-text"><%= @event.place %></p>
  </div>
</div>
<div id="owner" class="card mb-2">
  <h5 class="card-header"><%= Event.human_attribute_name(:owner) %></h5>
  <div class="card-body">
    <% if @event.owner %>
      <%= link_to("https://github.com/#{@event.owner.name}", class: 'card-link') do %>
        <%= image_tag @event.owner.image_url, width: 50, height: 50 %>
        <%= "@#{@event.owner.name}" %>
      <% end %>
    <% else %>
      退会済ユーザー
    <% end %>
  </div>
</div>
<div id="participants" class="card mb-2">
  <h5 class="card-header"><%= Event.human_attribute_name(:participants) %></h5>
  <div class="card-body">
    <% @tickets.each do |ticket| %>
      <% if ticket.user %>
        <%= link_to("https://github.com/#{ticket.user.name}", class: 'card-link') do %>
          <%= image_tag ticket.user.image_url, width: 50, height: 50 %>
          <%= "@#{ticket.user.name}" %>
        <% end %>
        <%= ticket.comment %>
      <% else %>
        退会済ユーザー
      <% end %>
    <% end %>
  </div>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/_show_footer.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% if @ticket %>
      <div class="col-auto">
        <%= link_to '参加をキャンセルする', event_ticket_path(@event, @ticket), method: :delete, data: { confirm: '本当にキャンセルしますか？' }, class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    <% else %>
      <% if logged_in? %>
        <div class="col-auto">
          <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">参加する</button>
          <%= render 'ticket_modal', locals: { event: @event } %>
        </div>
      <% else %>
        <div class="col-auto">
          <%= link_to '参加する', new_event_ticket_path(@event), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      <% end %>
    <% end %>
    <% if @event.created_by?(current_user) %>
      <div class="col-auto">
        <%= link_to 'イベント編集', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block' %>
      </div>
      <div class="col-auto">
        <%= link_to 'イベント削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか？' },  class: 'btn btn-danger btn-lg btn-block' %>
      </div>
    <% end %>
    <div class="col-auto">
      <%= link_to '戻る', 'javascript:history.back()', class: 'btn btn-secondary btn-lg btn-block' %>
    </div>
  </div>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/_ticket_modal.html.erb
<div class="modal dafe" id="createTicket">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="model-header pt-3 pl-3">
          <h4 class="modal-title" id="dialogHeader" class=""><%= Ticket.human_attribute_name(:comment) %></h4>
          <button class="close mr-3" type="button" data-dismiss="modal">&times;</button>
        </div>
        <%= form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f| %>
          <div class="modal-body">
            <div id="createTicketErrors">
              <%= f.text_field :comment, class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.button '送信', class: 'btn btn-primary' %>
            <button class="btn btn-secondary" type="button" data-dismiss="modal">キャンセル</button>
          </div>
        <% end %>
    </div>
  </div>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/edit.html.erb
<h1 class="mt-2">イベント編集</h1>
<%= render partial: 'form', locals: { event: @event, now: Time.zone.now } %>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/index.html.erb
<h1>イベント一覧</h1>
<%= render 'index_search_form' %>
<%= render 'shared/pagination_header', objects: @events %>
<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: 'list-group-item list-group-item-action') do %>
      <h5 class="list-group-item-heading"><%= event.name %></h5>
      <p class="mb-1"><%= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}" %></p>
    <% end %>
  <% end %>
</div>

<div class="pagination-content float-right mt-4">
  <%= paginate(@events) %>
</div>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/new.html.erb
<h1 class="mt-2">新規イベント登録</h1>
<%= render partial: 'form', locals: { event: @event, now: Time.zone.now } %>

ruby-on-rails/perfect-ruby-on-rails/app/views/events/show.html.erb
<h1 class="mt-3 mb-3"><%= @event.name %></h1>
<%= render 'show_body', locals: { event: @event, tickets: @tickets } %>
<%= render 'show_footer', locals: { event: @event, ticket: @ticket } %>

ruby-on-rails/perfect-ruby-on-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html" charset="utf-8" http-equiv="content-type">
    <title>イベント管理アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <header class="header navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <%= link_to 'イベント一覧', root_path, class: 'navbar-brand mr-auto' %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to '新規イベント登録', new_event_path, class: 'nav-link' %>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
                <%= link_to '退会', new_retirements_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete %>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to 'GitHubでログイン', '/auth/github', class: 'nav-link', method: :post %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    <div class="container mb-3">
      <% if flash.notice %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <% if flash.alert %>
        <div class="alert alert-danger">
          <%= flash.alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

<script>
  ((t, a, y, o, r, i) => {
    r = a.createElement(y);
    i = a.getElementsByTagName(y)[0];
    r.type='text/javascript';
    r.async=1
    r.src='//tayori.com/form/674fa5dd88e1fbb0cfe04ae1abdffd85be188f7c/tag.js';
    r.id='tayori-tag';
    i.parentNode.insertBefore(r,i);
  })(window,document,'script');
</script>

ruby-on-rails/perfect-ruby-on-rails/app/views/retirements/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: current_user.errors) %>"

ruby-on-rails/perfect-ruby-on-rails/app/views/retirements/new.html.erb
<h1 calss="mt-3">退会確認</h1>

<div id="errors"></div>

<p>退会するとユーザーに関する全ての情報が削除されます。</p>
<p>ただし、以下の場合は退会の操作を実行できません。</p>

<ul>
  <li>公開中の未終了イベントがある場合</li>
  <li>未終了の参加イベントがある場合</li>
</ul>

<hr>

<%= link_to '退会する', retirements_path, method: :post, remote: true, class: 'btn btn-danger', data: { confirm: '本当に退会しますか' } %>

ruby-on-rails/perfect-ruby-on-rails/app/views/shared/_pagination_header.html.erb
<% if defined?(objects) %>
<div class="pagination-field">
  <div class="pagination-wrapper">
    <div class="entry-content">
      <%= page_entries_info(objects, entry_name: objects&.model_name.to_s) %>
      <p class="display-items">
        表示件数：
        <% AppConfig[:number_per_page].each do |per| %>
          <%= link_to_unless per == objects.limit_value, per, { per: } %>
        <% end %>
         &nbsp;
      </p>
    </div>
    <div class="pagination-content float-right">
      <%= paginate(objects) %>
    </div>
  </div>
</div>
<% end %>

ruby-on-rails/perfect-ruby-on-rails/app/views/tickets/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @ticket.errors) %>"